name: Deploy Website to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Namecheap
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.NAMECHEAP_HOST }}
          username: ${{ secrets.NAMECHEAP_USERNAME }}
          key: ${{ secrets.NAMECHEAP_SSH_KEY }}
          port: ${{ secrets.NAMECHEAP_PORT }}
          source: "index.html,style.css"
          target: "/home/bloovzki/public_html"
